[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  '@openzeppelin/contracts=node_modules/@openzeppelin/contracts',
  '@manifoldxyz/libraries-solidity/=node_modules/@manifoldxyz/libraries-solidity/',
  '@manifoldxyz/creator-core-solidity/=node_modules/@manifoldxyz/creator-core-solidity/',
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
  '@zoralabs/protocol-rewards/src/=node_modules/@zoralabs/protocol-rewards/dist/contracts/',
  'erc721a-upgradeable/=node_modules/erc721a-upgradeable/contracts/'
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
